# Generated by Django 5.2.17 on 2026-09-08 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lot number order, lowest first."
                    ),
                ),
                (
                    "liquor",
                    models.CharField(
                        help_text="Hex colour of the brewed liquor. The page steeps into this on hover.",
                        max_length=7,
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        help_text="CSS background for the drawn tin, e.g. a linear-gradient().",
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Tasting note shown on the card and the lot page."
                    ),
                ),
                ("grade", models.CharField(max_length=80)),
                ("harvest", models.CharField(max_length=80)),
                (
                    "cup",
                    models.CharField(
                        help_text="Liquor colour and brewing guidance.", max_length=80
                    ),
                ),
                (
                    "tonnage",
                    models.CharField(help_text="Seasonal availability.", max_length=80),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Indicative FOB price band.", max_length=120
                    ),
                ),
                (
                    "leaf_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Dry- or wet-leaf photograph for the lot page. Falls back to the stand-in below.",
                        upload_to="lots/",
                    ),
                ),
                (
                    "leaf_photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback photo URL used until a real leaf photograph is uploaded.",
                    ),
                ),
                ("leaf_credit", models.CharField(blank=True, max_length=200)),
                ("leaf_credit_href", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50 – 100 kg", "50 – 100 kg"),
                            ("100 – 500 kg", "100 – 500 kg"),
                            ("500 kg – 1 tonne", "500 kg – 1 tonne"),
                            ("Over 1 tonne", "Over 1 tonne"),
                            ("Samples first", "Samples first"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("20 kg bulk chests", "20 kg bulk chests"),
                            ("50 g retail tins", "50 g retail tins"),
                            ("Private label", "Private label"),
                            ("Undecided", "Undecided"),
                        ],
                        max_length=40,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=160)),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Name and role"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Within a month", "Within a month"),
                            ("This quarter", "This quarter"),
                            ("Next flush", "Next flush"),
                            ("Just exploring", "Just exploring"),
                        ],
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "teas",
                    models.ManyToManyField(
                        blank=True, related_name="quote_requests", to="estate.tea"
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
    ]
